export const DATABASES_REQUEST = 'DATABASES_REQUEST'
export const DATABASES_SUCCESS = 'DATABASES_SUCCESS'
export const DATABASES_ERROR = 'DATABASES_ERROR'
export const DATABASES_CREATE = 'DATABASES_CREATE'
export const SET_CURRENT_DATABASE = 'SET_CURRENT_DATABASE'
export const DROP_DATABASE = 'DROP_DATABASE'

export const TABLES_REQUEST = 'TABLES_REQUEST'
export const TABLES_SUCCESS = 'TABLES_SUCCESS'
export const TABLES_ERROR = 'TABLES_ERROR'
export const TABLE_DROP = 'TABLE_DROP'


