export const TABLE_DATA_REQUEST = 'TABLE_DATA_REQUEST'
export const TABLE_DATA_ERROR = 'TABLE_DATA_ERROR'
export const TABLE_DATA_SUCCESS = 'TABLE_DATA_SUCCESS'
export const SET_CARRENT_TABLE = 'SET_CARRENT_TABLE'
